# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build bongo right"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      alphas: '["QWERTY"]'
      shield: '["corne_right"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y\nCONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=2048\nCONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=1\nCONFIG_ZMK_WPM=y\nCONFIG_ZMK_WIDGET_WPM_STATUS=y\nCONFIG_ZMK_WIDGET_BONGO_CAT=y\nCONFIG_ZMK_WIDGET_LAYER_STATUS=n\nCONFIG_ZMK_WIDGET_BATTERY_STATUS=n\nCONFIG_ZMK_WIDGET_OUTPUT_STATUS=n\n"]'
      modules: '["SamIAm2000/zmk/bongo-cat-dedicated-work-queue"]'
