# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build with gem screen"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      alphas: '["QWERTY"]'
      shield: '["kyria_left nice_view_adapter nice_view_gem","kyria_right nice_view_adapter nice_view_gem"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_STUDIO=y\nCONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y"]'
      modules: '["M165437/nice-view-gem/main"]'
