# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build with gem screen"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      alphas: '["QWERTY"]'
      shield: '["corne_left nice_oled","corne_right nice_oled"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y\nCONFIG_ZMK_STUDIO=y"]'
      modules: '["mctechnology17/zmk-nice-oled/main"]'
